# Generated by Django 5.2.4 on 2025-07-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyitem',
            name='is_active',
        ),
    ]
