# Generated by Django 5.2.4 on 2025-07-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_remove_supplyitem_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItemTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('received', 'Received'), ('issued', 'Issued')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to='supply.customuser')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to='supply.customuser')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplyitem')),
            ],
            options={
                'verbose_name': 'Supply Item Transaction',
                'verbose_name_plural': 'Supply Item Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
