# Generated by Django 5.2.4 on 2025-07-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_supplyitemtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
