# Generated by Django 5.2.4 on 2025-07-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_supplyitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('supplier', 'Supplier'), ('supply_manager', 'Supply Manager')], default='admin', max_length=20),
        ),
        migrations.CreateModel(
            name='SupplyManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'supply_manager'}, on_delete=django.db.models.deletion.CASCADE, to='supply.customuser')),
            ],
        ),
    ]
