# Generated by Django 5.2.4 on 2025-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_alter_customuser_user_type_supplymanagerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplymanagerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'supply_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
