# Generated by Django 5.2.4 on 2025-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_alter_supplierprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='supply_items',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='supply.supplyitem'),
        ),
    ]
