# Generated by Django 5.2.4 on 2025-07-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_supplierprofile_supply_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyitem',
            name='supplier',
        ),
    ]
