# Generated by Django 5.2.4 on 2025-08-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_remove_supplyitem_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierprofile',
            options={'permissions': [('can_view_supplier_dashboard', 'Can view supplier dashboard'), ('can_view_supplier_profile', 'Can view supplier profile'), ('can_view_supplier_orders', 'Can view supplier orders')], 'verbose_name': 'Supplier Profile', 'verbose_name_plural': 'Supplier Profiles'},
        ),
    ]
