# Generated by Django 5.2.4 on 2025-08-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0009_alter_supplierprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierprofile',
            options={'verbose_name': 'Supplier Profile', 'verbose_name_plural': 'Supplier Profiles'},
        ),
    ]
