# Generated by Django 5.2.4 on 2025-08-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0010_alter_supplierprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplymanagerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplymanagerprofile',
            name='phone',
        ),
    ]
