# Generated by Django 5.2.4 on 2025-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0011_remove_supplymanagerprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplymanagerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplymanagerprofile',
            name='employee_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='supplymanagerprofile',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supplymanagerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplymanagerprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
