# Generated by Django 5.2.4 on 2025-08-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0013_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
