# Generated by Django 5.2.4 on 2025-08-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0014_customerprofile_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
    ]
