# Generated by Django 5.2.4 on 2025-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0015_remove_customerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(),
        ),
    ]
