# Generated by Django 5.2.4 on 2025-09-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0016_remove_customerprofile_email_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyitemtransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='supplyitemtransaction',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='supplyitemtransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplyitemtransaction',
            name='initiated_by',
        ),
        migrations.RemoveField(
            model_name='supplyitemtransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='supplyitemtransaction',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.customerprofile'),
        ),
        migrations.AddField(
            model_name='supplyitemtransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Request'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplyitemtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REQUEST', 'Request'), ('DELIVERY', 'Delivery'), ('RETURN', 'Return')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupplyItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.customerprofile')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplyitem')),
            ],
        ),
    ]
