# Generated by Django 5.2.4 on 2025-09-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0017_alter_supplyitemtransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISCONTINUED', 'Discontinued')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplyitemrequest',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('FOR_DELIVERY', 'For Delivery'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplyitemtransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Request'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FOR_DELIVERY', 'For Delivery'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplyitemtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('DELIVERY', 'Delivery'), ('RETURN', 'Return')], max_length=20),
        ),
    ]
