# Generated by Django 5.2.4 on 2025-09-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0018_alter_supplyitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyitemtransaction',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Request'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FOR_DELIVERY', 'For Delivery'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
